int16 num
int64 time
string Needs
int8 CurOrder
int8 TotalOrder
float64 weight
int8 TotalTime
int8 satisfy_value      #需求满足强度的  预设值
int8 progress
# string HeadBehavior
# string HeadBehavior_person 
social_msg/Gaze gaze
social_msg/Emotion emotion
social_msg/Arms arms
social_msg/Speech speech
social_msg/Legs legs
string ExecutingBehavior
string ExecutingBehavior_person
string HeadBehavior
string HeadBehavior_person
int8 gaze_flag   
int8 emotion_flag
int8 arms_flag
int8 speech_flag
int8 legs_flag
bool Break_flag #是否为打断行为  1--是  0--否