<?xml version="1.0" ?>
<robot name="rm_65" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rm_65_description)/urdf/rm_65.transmission.xacro"/>
  <xacro:include filename="$(find rm_65_description)/urdf/rm_65.gazebo.xacro"/>
  <!-- <xacro:include filename="$(find rm_65_description)/urdf/common.gazebo.xacro"/> -->
  <!-- Inertial matrix -->
  <xacro:macro name="inertial_matrix" params="mass">
    <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>


  <!-- below is tracer -->
  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="urdf_extras" default="empty.urdf" />

  <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_1.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_2.xacro" />

  <xacro:include filename="$(find tracer_description)/urdf/fr_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fl_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rr_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rl_castor.xacro" />

  <xacro:include filename="$(find tracer_description)/urdf/fr_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fl_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rr_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rl_wheel.xacro" />



  <!-- Variables   -->  
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Vehicle Geometries -->
  <xacro:property name="base_x_size" value="0.6200000" />
  <xacro:property name="base_y_size" value="0.585000" />
  <xacro:property name="base_z_size" value="0.235000" />

  <xacro:property name="wheelbase" value="0.34"/><!--0.33515-->
  <xacro:property name="track" value="0.37910" /><!--0.37810-->

  <xacro:property name="castor_length" value="0.002"/>
  <xacro:property name="castor_radius" value="0.03724" />


  <xacro:property name="wheel_vertical_offset" value="-0.082" />
  <xacro:property name="castor_offset" value="0.03" />



  <xacro:property name="wheel_length" value="0.8e-01" />
  <xacro:property name="wheel_radius" value="1.600e-01" />

  <!-- Base link -->
  <link name="tracer_link">
      <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0"/>
          <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
          <geometry>
              <mesh filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
                <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
          </geometry>
      </visual>
      <collision>
        <!--origin
          xyz="-0.0145261552504705 0.0231316650320557 0.00586280190939592"
          rpy="0 0 0" /-->
          <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <mesh
            filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
            <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
        </geometry>
      </collision>
  </link>



  <link name="inertial_link">
      <inertial>
          <!--mass value="44.3898489950015" /-->
          <mass value="132.3898489950015" />
          <!-- <mass value="50" /> -->
          <!-- <origin xyz="-0.00065 -0.085 0.062" />
          <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
          <origin xyz="0.015 0.0231316650320557 0" />
          <!--<origin
            xyz="-0.0145261552504705 0.0231316650320557 0.00586280190939592"
            rpy="0 0 0" />-->
          <inertia ixx="0.185196122711036"
          ixy="4.30144213829512E-08"
          ixz="5.81037523686401E-08"
          iyy="0.364893736238929"
          iyz="-0.000386720198091934"
          izz="0.223868521722778" />
          <!--<inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />-->
      </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="tracer_link" />
      <child link="inertial_link" />
  </joint>


  <!-- tracer wheel macros -->
  <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
  <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
  <xacro:tracer_wheel_1 wheel_prefix="right">
      <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />     <!-- "wheel_vertical_offset" value="-0.082" /> -->
  </xacro:tracer_wheel_1>
  <xacro:tracer_wheel_2 wheel_prefix="left">
      <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
  </xacro:tracer_wheel_2>

<!--tracer castor wheel-->

  <xacro:fl_castor wheel_prefix="fl_castor">
      <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:fl_castor>
  <xacro:fr_castor wheel_prefix="fr_castor">
      <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:fr_castor>
  <xacro:rr_castor wheel_prefix="rr_castor">
      <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:rr_castor>
  <xacro:rl_castor wheel_prefix="rl_castor">
      <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:rl_castor>


  <xacro:fl_wheel wheel_prefix="fl">
      <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:fl_wheel>
  <xacro:fr_wheel wheel_prefix="fr">
      <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:fr_wheel>
  <xacro:rr_wheel wheel_prefix="rr">
      <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:rr_wheel>
  <xacro:rl_wheel wheel_prefix="rl">
      <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:rl_wheel>




  <!-- Additional definitions -->
  <!-- <xacro:include filename="$(arg urdf_extras)" /> -->

  <!-- Gazebo definitions  -->
  <xacro:include filename="$(find tracer_description)/urdf/tracer.gazebo" />





<joint name="tracer_joint" type="fixed">
      <origin xyz="0 0 0.0" rpy="0 0 3.14" />
      <parent link="tracer_link"/>
      <child link="base_link"/>
  </joint>








  <!-- Below is arm robot -->
  <link
    name="base_link">
    <inertial>
      <origin
        xyz="0.000364099338239377 -0.000180492589223954 0.0523748178864983"
        rpy="0 0 0" />
      <mass
        value="14" />
      <inertia
        ixx="0.000737277875726733"
        ixy="1.52768076655905E-06"
        ixz="-1.75138967359717E-05"
        iyy="0.000723643543181375"
        iyz="-8.08320706906158E-07"
        izz="0.000487026166065825" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/base_link.STL" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
    <mu1 value="200000.0"/>
    <mu2 value="200000.0"/>
    <kp value="100000000.0"/>
    <kd value="1.0"/>
  </gazebo>

  <link
    name="Link1">
    <inertial>
      <origin
        xyz="-1.79862733952242E-05 -0.0216004812887538 0.0719258896443856"
        rpy="0 0 0" />
      <mass
        value="0.200843839724735" />
      <inertia
        ixx="0.000531136984021332"
        ixy="-4.32776127280478E-07"
        ixz="1.04793272362077E-06"
        iyy="0.000497444611373595"
        iyz="0.000106254355496355"
        izz="0.000282103590137435" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint1"
    type="revolute">
    <origin
      xyz="0.00019414 0.0001 0.138"
      rpy="-2.3944E-16 0 3.1416" />
    <parent
      link="base_link" />
    <child
      link="Link1" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="300"
      velocity="3.14" />
	<dynamics damping="50" friction="1"/>
  </joint>
  <link
    name="Link2">
    <inertial>
      <origin
        xyz="0.133181684940056 -4.09216469913973E-05 0.0184216581306229"
        rpy="0 0 0" />
      <mass
        value="0.321307361964397" />
      <inertia
        ixx="0.000440014028766832"
        ixy="5.6579315252598E-07"
        ixz="-0.000654853772254918"
        iyy="0.00298539844077015"
        iyz="1.20748806355071E-07"
        izz="0.00284806640328522" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link2.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint2"
    type="revolute">
    <origin
      xyz="0 0.016171 0.1012"
      rpy="1.5708 -1.5708 0" />
    <parent
      link="Link1" />
    <child
      link="Link2" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2.269"
      upper="2.269"
      effort="300"
      velocity="3.14" />
	<dynamics damping="50" friction="1"/>
  </joint>
  <link
    name="Link3">
    <inertial>
      <origin
        xyz="-3.56690328818382E-06 -0.0512866037910138 2.10951876323563E-05"
        rpy="0 0 0" />
      <mass
        value="0.102772515618803" />
      <inertia
        ixx="0.000236471825455939"
        ixy="-2.85439143488268E-09"
        ixz="-4.04883470632046E-10"
        iyy="7.36858171850124E-05"
        iyz="5.2218422744868E-05"
        izz="0.000233873582444284" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link3.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint3"
    type="revolute">
    <origin
      xyz="0.25576 0 0.0035251"
      rpy="1.1972E-16 1.4979E-28 1.5708" />
    <parent
      link="Link2" />
    <child
      link="Link3" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2.356"
      upper="2.356"
      effort="300"
      velocity="3.14" />
	<dynamics damping="50" friction="1"/>
  </joint>
  <link
    name="Link4">
    <inertial>
      <origin
        xyz="6.79143687717758E-05 0.0172073813582943 0.0550497562490089"
        rpy="0 0 0" />
      <mass
        value="0.0751534548575527" />
      <inertia
        ixx="0.000114971629184183"
        ixy="1.55043636696422E-08"
        ixz="2.03173541830271E-07"
        iyy="0.000105991655073516"
        iyz="-2.1400189980959E-05"
        izz="5.71243912493456E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link4.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link4.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint4"
    type="revolute">
    <origin
      xyz="0 -0.128 0.013234"
      rpy="1.5708 0 1.2512E-12" />
    <parent
      link="Link3" />
    <child
      link="Link4" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="300"
      velocity="3.14" />
	<dynamics damping="50" friction="1"/>
  </joint>
  <link
    name="Link5">
    <inertial>
      <origin
        xyz="-2.14593281051834E-06 -0.049119542458982 0.00236936437088902"
        rpy="0 0 0" />
      <mass
        value="0.0716575200885179" />
      <inertia
        ixx="0.000135381803103201"
        ixy="2.17516760135376E-09"
        ixz="8.55618321137308E-10"
        iyy="4.67751191123099E-05"
        iyz="2.92366122866633E-05"
        izz="0.000132066640473067" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link5.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link5.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint5"
    type="revolute">
    <origin
      xyz="0 -0.0121 0.0815"
      rpy="-1.5708 2.359E-12 5.6484E-28" />
    <parent
      link="Link4" />
    <child
      link="Link5" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2.182"
      upper="2.182"
      effort="300"
      velocity="3.14" />
	<dynamics damping="50" friction="1"/>
  </joint>
  <link
    name="Link6">
    <inertial>
      <origin
        xyz="0.000610923552198394 0.000226239439845178 0.0217158471531674"
        rpy="0 0 0" />
      <mass
        value="0.0321480840686874" />
      <inertia
        ixx="1.19996413785174E-05"
        ixy="-2.82372207081771E-08"
        ixz="9.42210764600823E-08"
        iyy="1.15507239688493E-05"
        iyz="-4.23625640293711E-08"
        izz="1.77260433647625E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link6.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://rm_65_description/meshes/Link6.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint6"
    type="revolute">
    <origin
      xyz="0 -0.115 0.012437"
      rpy="1.5708 0 -2.359E-12" />
    <parent
      link="Link5" />
    <child
      link="Link6" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.28"
      upper="6.28"
      effort="300"
      velocity="1" />
	<dynamics damping="50" friction="1"/>
  </joint>

<!-- camera  <mesh  filename="package://rm_65_description/meshes/akdk_camera_cad1.STL" />
          <box size="0.2 0.3 0.3"/>
          -->
<!-- kinect -->
  <xacro:include filename="$(find rm_65_description)/urdf/yixiuge_d435i.xacro" />
  <!--添加d435i的link即joint -->
  <xacro:yixiuge_d435i>     </xacro:yixiuge_d435i>
  <joint name="yixiuge_kinect_base_joint" type="fixed">
    <origin xyz="0.0 0.0 0.05" rpy="0 0 0" />
    <parent link="Link6"/>
    <child link="camera_base_link"/>
  </joint> 


    <!-- Transmissions for ROS Control -->
    <xacro:macro name="transmission_block" params="joint_name">
        <transmission name="tran1">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor1">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <xacro:transmission_block joint_name="joint1"/>
    <xacro:transmission_block joint_name="joint2"/>
    <xacro:transmission_block joint_name="joint3"/>
    <xacro:transmission_block joint_name="joint4"/>
    <xacro:transmission_block joint_name="joint5"/>
    <xacro:transmission_block joint_name="joint6"/>

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/arm</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>
</robot>
